In [ ]:
# TITULO: MODELO PARA LA EVALUACIÓN DE FOTOMULTAS EN CDMX
# AUTOR: EDUARDO HERNANDEZ MARTINEZ
# FECHA DE ULTIMA MODIFICACION: 05/05/2026
#----------------------------------------------- DECLARACIÓN DE LIBRERÍAS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from geopy.distance import geodesic
#----------------------------------- CARGA DE LOS DATOS
df1 = pd.read_csv('inViales_2014_2015.csv', on_bad_lines='skip')
df2 = pd.read_csv('inViales_2016_2018.csv', on_bad_lines='skip')
df3 = pd.read_csv('inViales_2019_2021.csv', on_bad_lines='skip')
df4 = pd.read_csv('inViales_2022_2024.csv', on_bad_lines='skip')

fotomultas = pd.read_csv('fotomultas.csv')



# LIMPIEZA DE DATOS

Análisis somero

In [ ]:
df1.head()

,folio,fecha_creacion,hora_creacion,dia_semana,fecha_cierre,hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud
0,C4/140101/02301,2014-01-01,13:24:48,Miércoles,2014-01-01,16:49:00,Accidente,Choque sin lesionados,IZTAPALAPA,A,EMERGENCIA,LLAMADA DEL 066,IZTAPALAPA,Iztapalapa,Leyes De Reforma 3a Seccion,-99.06104,19.38090
1,C4/140101/04188,2014-01-01,21:44:59,Miércoles,2014-01-01,21:55:02,Accidente,Choque sin lesionados,GUSTAVO A. MADERO,A,EMERGENCIA,LLAMADA DEL 066,GUSTAVO A. MADERO,Gustavo A. Madero,Martin Carrera,-99.10342,19.49053
2,C4/131231/03155,2013-12-31,22:03:13,Martes,2014-01-01,00:08:24,Accidente,Choque sin lesionados,IZTAPALAPA,I,EMERGENCIA,RADIO,IZTAPALAPA,Iztapalapa,Polvorilla,-99.04830,19.32276
3,C4/131231/03346,2013-12-31,22:44:53,Martes,2014-01-01,02:11:35,Accidente,Choque sin lesionados,IZTAPALAPA,I,EMERGENCIA,LLAMADA DEL 066,IZTAPALAPA,Iztapalapa,Barrio Guadalupe,-99.07113,19.31469
4,C4/140101/04189,2014-01-01,21:45:43,Miércoles,2014-01-01,23:55:59,Accidente,Choque con lesionados,ALVARO OBREGON,A,URGENCIAS MEDICAS,LLAMADA DEL 066,ALVARO OBREGON,Álvaro Obregón,Los Alpes,-99.19104,19.36336

In [ ]:
df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356072 entries, 0 to 356071
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   folio              356072 non-null  object
 1   fecha_creacion     356072 non-null  object
 2   hora_creacion      356072 non-null  object
 3   dia_semana         356072 non-null  object
 4   fecha_cierre       356072 non-null  object
 5   hora_cierre        356072 non-null  object
 6   tipo_incidente_c4  356072 non-null  object
 7   incidente_c4       356072 non-null  object
 8   alcaldia_inicio    355997 non-null  object
 9   codigo_cierre      356072 non-null  object
 10  clas_con_f_alarma  356072 non-null  object
 11  tipo_entrada       356072 non-null  object
 12  alcaldia_cierre    355997 non-null  object
 13  alcaldia_catalogo  354560 non-null  object
 14  colonia_catalogo   349708 non-null  object
 15  longitud           356072 non-null  float64
 16  latitud            356072 non-null  float64
dtypes: float64(2), object(15)
memory usage: 46.2+ MB

            longitud        latitud
count  356072.000000  356072.000000
mean      -99.138344      19.386641
std         0.060165       0.068461
min       -99.354499      19.094020
25%       -99.179380      19.340090
50%       -99.140900      19.387140
75%       -99.099020      19.436930
max       -98.945370      19.578570

Renombramos las columnas reducirlas y normalizarlas

In [ ]:
df1 = df1.rename(columns={
    'fecha_creacion': 'fecha',
    'hora_creacion': 'hora',
    'tipo_incidente_c4': 'categoria',
    'incidente_c4': 'secuelas'
})

In [ ]:
df2 = df2.rename(columns={
    'fecha_creacion': 'fecha',
    'hora_creacion': 'hora',
    'tipo_incidente_c4': 'categoria',
    'incidente_c4': 'secuelas'
})

In [ ]:
df3 = df3.rename(columns={
    'fecha_creacion': 'fecha',
    'hora_creacion': 'hora',
    'tipo_incidente_c4': 'categoria',
    'incidente_c4': 'secuelas'
})

In [ ]:
df4 = df4.rename(columns={
    'fecha_creacion': 'fecha',
    'hora_creacion': 'hora',
    'tipo_incidente_c4': 'categoria',
    'incidente_c4': 'secuelas'
})

Se estableccen las columnas que nos aportan información para nuestro código como columnas importantes

In [ ]:
columnas_importantes= ['fecha', 'hora', 'categoria','secuelas', 'alcaldia_inicio' ,'latitud', 'longitud']
df1=df1[columnas_importantes]
df2=df2[columnas_importantes]
df3=df3[columnas_importantes]
df4=df4[columnas_importantes]

Normalizamos la columna de fecha en las 4 tablas

In [ ]:
df1['fecha'] = pd.to_datetime(df1['fecha'], errors='coerce')
df2['fecha'] = pd.to_datetime(df2['fecha'], errors='coerce')
df3['fecha'] = pd.to_datetime(df3['fecha'], errors='coerce')
df4['fecha'] = pd.to_datetime(df4['fecha'], errors='coerce')

Verificamos si hay incidentes con coordenadas nulas o 0 en las 4 tablas

In [ ]:
print(df1['latitud'].isna().sum())
print((df1['latitud']==0).sum())
print(df1['longitud'].isna().sum())
print((df1['longitud']==0).sum())

0
0
0
0

In [ ]:
print(df2['latitud'].isna().sum())
print((df2['latitud']==0).sum())
print(df2['longitud'].isna().sum())
print((df2['longitud']==0).sum())

0
6
0
14

In [ ]:
print(df3['latitud'].isna().sum())
print((df3['latitud']==0).sum())
print(df3['longitud'].isna().sum())
print((df3['longitud']==0).sum())

0
0
0
0

In [ ]:
print(df4['latitud'].isna().sum())
print((df4['latitud']==0).sum())
print(df4['longitud'].isna().sum())
print((df4['longitud']==0).sum())

0
0
0
0

Al solo contar con el 2do dataset con valores vacíos en la ubicación entonces se eliminan esos datos ya que son una cantidad minima

In [ ]:
df2 = df2[(df2['latitud'] != 0) & (df2['longitud'] != 0)]
df2 = df2.dropna(subset=['latitud', 'longitud'])

In [ ]:
print(df2['latitud'].isna().sum())
print((df2['latitud']==0).sum())
print(df2['longitud'].isna().sum())
print((df2['longitud']==0).sum())

0
0
0
0

Comprobamos que no haya nada raro en la columna de alcaldia_inicio

In [ ]:
df1['alcaldia_inicio'].unique()

array(['IZTAPALAPA', 'GUSTAVO A. MADERO', 'ALVARO OBREGON', 'TLAHUAC',
       'AZCAPOTZALCO', 'COYOACAN', 'CUAUHTEMOC', 'IZTACALCO',
       'LA MAGDALENA CONTRERAS', 'VENUSTIANO CARRANZA', 'TLALPAN',
       'BENITO JUAREZ', 'XOCHIMILCO', 'MILPA ALTA', 'MIGUEL HIDALGO',
       'CUAJIMALPA DE MORELOS', nan], dtype=object)

In [ ]:
df2['alcaldia_inicio'].unique()

array(['CUAJIMALPA DE MORELOS', 'IZTAPALAPA', 'AZCAPOTZALCO',
       'VENUSTIANO CARRANZA', 'TLALPAN', 'COYOACAN', 'CUAUHTEMOC',
       'MIGUEL HIDALGO', 'ALVARO OBREGON', 'XOCHIMILCO',
       'GUSTAVO A. MADERO', 'LA MAGDALENA CONTRERAS', 'IZTACALCO',
       'BENITO JUAREZ', 'TLAHUAC', 'MILPA ALTA', nan], dtype=object)

In [ ]:
df3['alcaldia_inicio'].unique()

array(['IZTAPALAPA', 'BENITO JUAREZ', 'CUAUHTEMOC', 'COYOACAN', 'TLAHUAC',
       'GUSTAVO A. MADERO', 'VENUSTIANO CARRANZA', 'MIGUEL HIDALGO',
       'XOCHIMILCO', 'TLALPAN', 'CUAJIMALPA DE MORELOS', 'IZTACALCO',
       'ALVARO OBREGON', 'AZCAPOTZALCO', 'MILPA ALTA',
       'LA MAGDALENA CONTRERAS', nan], dtype=object)

In [ ]:
df4['alcaldia_inicio'].unique()

array([nan, 'CUAUHTEMOC', 'IZTACALCO', 'VENUSTIANO CARRANZA',
       'GUSTAVO A. MADERO', 'XOCHIMILCO', 'TLAHUAC', 'IZTAPALAPA',
       'MIGUEL HIDALGO', 'ALVARO OBREGON', 'AZCAPOTZALCO', 'TLALPAN',
       'COYOACAN', 'MILPA ALTA', 'CUAJIMALPA DE MORELOS', 'BENITO JUAREZ',
       'LA MAGDALENA CONTRERAS'], dtype=object)

Ya que todas los datos de las tablas se encuentran en buen estado los podemos juntar en una sola tabla

In [ ]:
df_incidentes = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [ ]:
duplicados= df_incidentes.duplicated()
duplicados.sum()

np.int64(2293)

In [ ]:
df_incidentes[df_incidentes.duplicated()]

,fecha,hora,categoria,secuelas,alcaldia_inicio,latitud,longitud
604,2014-01-03,08:27:00,Accidente,Choque con lesionados,GUSTAVO A. MADERO,19.46809,-99.13552
702,2014-01-03,16:24:00,Lesionado,Atropellado,IZTAPALAPA,19.32076,-99.08739
775,2014-01-03,19:06:00,Lesionado,Atropellado,BENITO JUAREZ,19.39586,-99.15607
881,2014-01-03,00:44:00,Accidente,Choque con lesionados,CUAUHTEMOC,19.40619,-99.16321
3358,2014-01-10,15:00:08,Lesionado,Atropellado,GUSTAVO A. MADERO,19.47507,-99.08872
...,...,...,...,...,...,...,...
2100822,2024-02-08,00:32:42,Accidente,Choque con lesionados,IZTACALCO,19.40254,-99.12146
2100824,2024-02-08,00:33:11,Accidente,Choque con lesionados,IZTACALCO,19.40254,-99.12146
2102701,2024-02-11,13:01:54,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,19.42932,-99.10408
2113934,2024-02-28,13:16:35,Accidente,Choque sin lesionados,COYOACAN,19.34370,-99.15649
2113987,2024-02-28,13:44:24,Lesionado,Atropellado,GUSTAVO A. MADERO,19.50935,-99.15926

Eliminamos todos aquellos incidentes duplicados

In [ ]:
df_incidentes = df_incidentes.drop_duplicates()

Una vez tenemos limpios los incidentes los convertimos en un archivo

In [ ]:
df_incidentes.to_csv('incidentes_limpio.csv', index=False)

In [ ]:
fotomultas.head()

,id,via_princi,ubicacion,sentido,latitud,longitud
0,52,Viaducto R?o de la Piedad,Viaducto R?o de la Piedad y 1ro de Mayo,Poniente a Oriente,19.405605,-99.119721
1,3,Circuito Bicentenario Maestro Jos? Vasconcelos,Circuito Bicentenario Maestro Jos? Vasconcelos...,Norte a Sur,19.407957,-99.184197
2,2,Fray Servando,Escuela M?dico Militar - Jos? Antonio Torres X...,Poniente a Oriente,19.423568,-99.131166
3,27,Eje Central,Eje Central L?zaro C?rdenas y Av. Ricardo Flor...,Sur a Norte,19.449558,-99.138399
4,90,Perif?rico 2P S-N,Perif?rico 2P S-N / R?o San ?ngel y Rinc. Atla...,Norte a Sur,19.354244,-99.199933

Analizamos cuales camaras no contaban con coordenadas

In [ ]:
print(fotomultas['latitud'].isna().sum())
print((fotomultas['latitud']==0).sum())
print(fotomultas['longitud'].isna().sum())
print((fotomultas['longitud']==0).sum())

27
0
27
0

Obtenemos el resultado de camaras con datos faltantes

In [ ]:
total = len(fotomultas)
# vacios en cualquiera de las dos
na_total = fotomultas[['latitud', 'longitud']].isna().any(axis=1).sum()

print(f"Registros vacios en latitud o longitud: {na_total} ({na_total/total*100:.2f}%)")

Registros vacios en latitud o longitud: 27 (19.29%)

Debido a que representa menos de un 20% y no podemos tener la capacidad de predecir la ubicación de las demás, optamos por eliminar aquellos registros con ubicacion nula

In [ ]:
fotomultas_limpio = fotomultas.dropna(subset=['latitud', 'longitud']).copy()

print(f"Registros originales: {len(fotomultas)}")
print(f"Registros limpios: {len(fotomultas_limpio)}")

Registros originales: 140
Registros limpios: 113

In [ ]:
print(fotomultas_limpio['latitud'].isna().sum())
print((fotomultas_limpio['latitud']==0).sum())
print(fotomultas_limpio['longitud'].isna().sum())
print((fotomultas_limpio['longitud']==0).sum())

0
0
0
0

Normalizamos el texto para evitar errores de código

In [ ]:
fotomultas_limpio['via_princi'] = fotomultas_limpio['via_princi'].str.normalize('NFKD') \
    .str.encode('ascii', errors='ignore') \
    .str.decode('utf-8')

In [ ]:
fotomultas_limpio.head()

,id,via_princi,ubicacion,sentido,latitud,longitud
0,52,Viaducto R?o de la Piedad,Viaducto R?o de la Piedad y 1ro de Mayo,Poniente a Oriente,19.405605,-99.119721
1,3,Circuito Bicentenario Maestro Jos? Vasconcelos,Circuito Bicentenario Maestro Jos? Vasconcelos...,Norte a Sur,19.407957,-99.184197
2,2,Fray Servando,Escuela M?dico Militar - Jos? Antonio Torres X...,Poniente a Oriente,19.423568,-99.131166
3,27,Eje Central,Eje Central L?zaro C?rdenas y Av. Ricardo Flor...,Sur a Norte,19.449558,-99.138399
4,90,Perif?rico 2P S-N,Perif?rico 2P S-N / R?o San ?ngel y Rinc. Atla...,Norte a Sur,19.354244,-99.199933

Analizamos todas las vialidades que aparecen en nuestra columna via principal

In [ ]:
fotomultas_limpio['via_princi'].unique()

array(['Viaducto R?o de la Piedad',
       'Circuito Bicentenario Maestro Jos? Vasconcelos', 'Fray Servando',
       'Eje Central', 'Perif?rico 2P S-N', 'Autopista Urbana Norte (AUN)',
       'Universidad', 'Circuito Bicentenario Av. Rio Churubusco',
       'Eje 1 Oriente', 'Eje 1 Poniente Guerrero', 'Arcos de Bel?n',
       'Av. Insurgentes Nte.', 'Av. Marina Nacional',
       'Av. Rivera de San Cosme y Santa Mar?a La Rivera',
       'Av. Paseo de la Reforma', 'Poniente a Oriente',
       'Fray Servando Teresa de Mier', 'Calz. Ignacio Zaragoza',
       'Av. Ocean?a', 'Chapultepec', 'Calz. Gral. Ignacio Zaragoza',
       'Guadalupe I. Ramirez',
       'Av. Hidalgo - Paseo de la Reforma y Zarco', 'Av. Aquiles Serd?n',
       'Eje 3 Poniente',
       'Circuito Bicentenario Av. Rio Consulado y Av. Ing. Eduardo Molina',
       'Eje Central Lazaro Cardenas y Circuito Bicentenario Paseo de las Jacarandas',
       'Anillo Perif?rico Canal de Garay', 'Calz. De Tlalpan',
       'San Lorenzo y Eje 8 Sur', 'Circuito Bicentenario Melchor Ocampo',
       'Eje 6 Sur Narciso Mendoza', 'Eje 4 Oriente', 'Eje 6 Sur',
       'Pino Su?rez', 'Eje 2 Nte. Manuel Gonz?lez',
       'Eje Central L?zaro C?rdenas', 'Eje 5 Av. Montevideo',
       'Circuito Bicentenario Instituto T?cnico Industrial',
       'Circuito Bicentenario Boulebard Puerto Aereo',
       'Eje 8 Sur Ermita Iztapalapa', 'Eje 1 Nte. Mosqueta',
       'Av. Ej?rcito Nacional Mexicano', 'Eje 3 Oriente',
       'Eje 2 Oriente La viga y Circuito Bicentenario Rio Churubusco',
       'Eje 5 Sur', 'Eje 3 Sur', 'Eje 1 Norte', 'Zaragoza',
       'Circuito Bicentenario Av. R?o Consulado', 'Av. Canal del Nte.',
       'Eje 2 Norte', 'Av. Revolucion - Eje 10 Sur Loreto',
       'Calz. Vallejo', 'Eje 7 Sur Municipio Libre y Division del Norte',
       'Av. Revoluci?n', 'Revoluci?n', 'Av. Constituyentes',
       'Circuito Bicentenario Calz. Melchor Ocampo',
       'Eje 3 Sur Jos? Pe?n', 'Anillo Perif?rico',
       'Av. Instituto Polit?cnico Nacional', 'Marina Nacional', 'Izazaga',
       'Andr?s Molina Enr?quez', 'Taxque?a',
       'Paseo de la Reforma - Eje 1 Poniente - Ju?rez',
       'Calzada de Misterios', 'Av. Tlahuac y Ganaderos', 'Eje 8 Sur',
       'Eje 8 Sur y Av. Universidad', 'Av. Ej?rcito Nacional',
       'Av. Chapultepec', 'Av.608', 'Paseo de la Reforma', 'Perif?rico',
       'Insurgentes', 'Av. Calzada Ignacio Zaragoza',
       'Calz. Gral. Mariano Escobedo y Laguna de T?rminos',
       'Eje 1 Nte. Jos? Antonio ?lzate'], dtype=object)

In [ ]:
fotomultas_limpio['ubicacion'].unique()

array(['Viaducto R?o de la Piedad y 1ro de Mayo',
       'Circuito Bicentenario Maestro Jos? Vasconcelos y Av. Benjam?n Franklin',
       'Escuela M?dico Militar - Jos? Antonio Torres Xocongo y Fray Servando Teresa de Mier',
       'Eje Central L?zaro C?rdenas y Av. Ricardo Flores Mag?n',
       'Perif?rico 2P S-N / R?o San ?ngel y Rinc. Atlamaya',
       'AUN / Av. R?o Becerra y 11 de Abril',
       'Perif?rico 2P S-N / Etna y Ajusco',
       'Eje 9 Sur Miguel ?ngel de Quevedo y Av. Universidad',
       'Circuito Bicentenario Av. Rio Churubusco y Gerentes',
       'Eje 1 Oriente Av. del Trabajo, Eje 2 Norte Canal del Norte y Av. Circunvalaci?n',
       'Eje 1 Poniente Guerrero y Eje 2 Norte Manuel Gonz?lez',
       'Jose Maria Izazaga y Eje Central L?zaro C?rdenas',
       'Av. Insurgentes Nte. y Pte. 112',
       'Av. Marina Nacional y Felipe Carrillo Puerto', 'Av. San Cosme',
       'Av. Paseo de la Reforma y Estela  de Luz', 'Av. Cuitl?huac',
       'AUN /Gral. Juan Cabral y Batalla de Celaya',
       'Fray Servando Teresa de Mier y Cucurpe',
       'Calz. Ignacio Zaragoza y Anselmo de la Portilla',
       'Av. Ocean?a y Pablo R. Sidar', 'Chapultepec - Sonora - Lieja',
       'Calz Gral. Ignacio Zaragoza y Circuito Bicentenario Boulevard Puerto  A?reo',
       'Av. Guadalupe I. Ram?rez y Prol. Divisi?n del Norte',
       'Av. Hidalgo', 'Av. Aquiles Serd?n y Av. Tezozomoc',
       'Eje 3 Pte. Thiers y Darwin',
       'Circuito Bicentenario Av. Rio Consulado',
       'Eje Central Lázaro Cárdenas',
       'Anillo Perif?rico Canal de Garay y Lebrija',
       'Calz. De Tlalpan y Museo', 'San Lorenzo',
       'Perif?rico 2P S-N / Dr. Glez. Herrej?n / Lomas de Plateros',
       'Circuito Bicentenario Melchor Ocampo y R?o Duero',
       'Eje 6 Sur Narciso Mendoza y  Eje 8 Sur Ermita Iztapalapa',
       'Eje 4 Ote. Canal Rio Churubusco y Canal de Apatlaco',
       'Eje 6 Sur Av. Luis M?ndez y Carlos L Gracidas',
       'Jos? Mar?a Pino Su?rez y Venustiano Carranza',
       'Eje 2 Nte. Manuel Gonz?lez y Calle General Ignacio Zaragoza',
       'Eje Central L?zaro C?rdenas y Toribio Medina',
       'Eje Central L?zaro C?rdenas y Avenida Hidalgo',
       'Eje 5 Av. Montevideo y Pulacayo',
       'Circuito Bicentenario Instituto T?cnico Industrial y Calle Eligio Ancona',
       'Circuito Bicentenario Boulebard Puerto Aereo y Norte 25',
       'Av. Insurgentes Nte. y Av. Ricarte',
       'Eje 8 Sur Ermita Iztapalapa y Roc?o',
       'Perif?rico 2P S-N Calz. Catarina y Av. Le?n Felipe',
       'Eje Central L?zaro C?rdenas y Fortuna',
       'Eje 1 Nte. Mosqueta y Soto',
       'Av. Ej?rcito Nacional Mexicano y Anillo Perif?rico Boulevard Manuel ?vila Camacho',
       'Eje 3 Oriente Ing. Eduardo Molina y Eje 5 Norte San Juan de Arag?n',
       'Eje 2 Oriente', 'Eje 5 Sur y Anillo Periferico Oriente',
       'AUN /  Calle 16 y Av. San Antonio',
       'Eje 3 Sur (Dr. Morones Prieto) y Dr. Jos? Ma. V?rtiz',
       'Eje 1 Norte - Insurgentes - Buenavista',
       'Calz Gral. Ignacio Zaragoza y Viaducto',
       'AUN /   Fernando Alencastre y Av. de los Constituyentes',
       'Circuito Bicentenario Av. R?o Consulado y Cant?n',
       'Av. Canal del Nte. y Tenochtitl?n',
       'Eje 2 Norte Manuel Gonz?lez y Eje Central L?zaro C?rdenas',
       'Av. Revolución', 'Perif?rico 2P S-N Aurelio Rivera/Pino',
       'Calz. Vallejo y Cuauht?moc',
       'Calz. Gral. Ignacio Zaragoza y Circuito Bicentenario Boulevard Puerto  A?reo',
       'Eje 7 Sur', 'Av. Revoluci?n y Calle 13',
       'AUN / Deportivo Israelita /Ing. Zapadores y Av. del Conscripto',
       'Eje 6 Sur Playa Pie de la Cuesta y Eje 1 Ote. Andr?s Molina Enr?quez',
       'Eje 4 Pte. Av. Revoluci?n y Av. Barranca del Muerto',
       'Av. Constituyentes y Gob. Gregorio Villa Gelati',
       'Calz. De Tlalpan y Calle Atletas',
       'AUN / Av. Ej?rcito Nacional y Miguel de Cervantes Saavedra',
       'AUN / Gobernador Jos? Ceballos y Av. Constituyentes',
       'Circuito Bicentenario Calz. Melchor Ocampo y Nezahualpilli',
       'Eje 3 Sur Jos? Pe?n y Contreras y Jos? Mar?a Bustillos',
       'Anillo Perif?rico y Embarcadero del Parque Ecol?gico de Xochimilco',
       'Calz. Ignacio Zaragoza y Primavera',
       'Av. Instituto Polit?cnico Nacional y Eje 5 Nte Montevideo',
       'Calz Gral. Mariano Escobedo y Av. Marina Nacional',
       'Jos? Mar?a Izazaga y Jos? Mar?a Pino Su?rez',
       'Eje 2 Norte Canal del Norte y Av. Circunvalaci?n y Eje 1 Oriente Av. del Trabajo',
       'Eje 1 Ote. Andr?s Molina Enr?quez y Eje 5 Sur Playa Villa del Mar',
       'Eje 9 Sur Taxque?a y Eje 1 Oriente Canal de Miramontes',
       'Eje 1 Poniente',
       'Perif?rico 2P S-N / Miguel Cabrera y La Casta?eda',
       'Calzada de Misterios y Eje 3 Norte Av. Alfredo Robles Dom?nguez',
       'Av. Constituyentes y Camino de los Toros', 'Av. Tláhuac',
       'Av. Instituto Polit?cnico Nacional y Av. Ricarte',
       'Eje 8 Sur Ermita Iztapalapa y Eje 5 Ote Av. Rojo G?mez',
       'Eje 8 Sur', 'Av. Ej?rcito Nacional y Calle Luis Vives',
       'Eje 5 Av. Montevideo y Nte. 31-A', 'Av. Chapultepec y Guaymas',
       'Av.608 y Av. 508',
       'Paseo de la Reforma y Eje Central L?zaro C?rdenas y Eje 1 Norte Mosqueta',
       'Eje 8 Sur Ermita Iztapalapa y Eje 6 Sur Narciso Mendoza',
       'Perif?rico Oriente Canal de Garay - Av. Tl?huac y San Lorenzo',
       'Insurgentes Buenavista y Eje 1 Norte',
       'Av. Calzada Ignacio Zaragoza y Azc?rraga Vidaurreta',
       'Calz. Gral. Mariano Escobedo',
       'Eje 1 Nte. Jos? Antonio ?lzate y Naranjo',
       'Circuito Bicentenario Av. R?o Consulado y Av. Encarnaci?n Ort?z',
       'Eje 1 Norte Mosqueta - Paseo de la Reforma y Eje Central L?zaro C?rdenas',
       'Eje 1 Oriente Canal de Miramontes y Eje 9 Sur Taxque?a y Cerro de Teponaxtle',
       'Av. Paseo de la Reforma e Ignacio Allende',
       'Eje Central y Margarita Maza de Juarez',
       'Calz. Vallejo y Calle Pino Su?rez',
       'Circuito Bicentenario Av. R?o Consulado y Av. Congreso de la Uni?n',
       'Perif?rico 2P S-N/Cda las Flores y Calz de las ?guilas'],
      dtype=object)

Tomamos las columnas que hacen sentido para el análisis de nuestro proyecto

In [ ]:
columnas_importantes= ['via_princi','sentido','latitud','longitud']
fotomultas_limpio=fotomultas_limpio[columnas_importantes]

In [ ]:
fotomultas_limpio.head()

,via_princi,sentido,latitud,longitud
0,Viaducto R?o de la Piedad,Poniente a Oriente,19.405605,-99.119721
1,Circuito Bicentenario Maestro Jos? Vasconcelos,Norte a Sur,19.407957,-99.184197
2,Fray Servando,Poniente a Oriente,19.423568,-99.131166
3,Eje Central,Sur a Norte,19.449558,-99.138399
4,Perif?rico 2P S-N,Norte a Sur,19.354244,-99.199933

Lo convertimos a un documento de valores separado por comas

In [ ]:
fotomultas_limpio.to_csv('fotomultas_preliminar.csv', index=False)